default: &default
  adapter: postgresql
  encoding: unicode
  user: usuario
  password: senhausuario
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pedido_rapido_development

test:
  <<: *default
  database: pedido_rapido_test
  username: usuario
  password: senhausuario

production:
  <<: *default
  database: pedido_rapido_production
  username: usuario
  password: <%= ENV['PEDIDO_RAPIDO_DATABASE_PASSWORD'] %>
